package com.apnabazaar.controller;

import com.apnabazaar.service.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.transaction.annotation.Transactional;
import jakarta.servlet.http.HttpServletRequest;
import java.util.*;
import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;

@RestController @RequestMapping("/api/{slug}")
public class ProviderReputationController {
 private final JdbcTemplate jdbc; private final ResidentService residents; private final MessageModerationService moderation;
 private final ChatRateLimiter limiter; private final String key; private final boolean proxy;
 public ProviderReputationController(JdbcTemplate jdbc,ResidentService residents,MessageModerationService moderation,ChatRateLimiter limiter,@Value("${CAMPAIGN_ADMIN_TOKEN:}")String key,@Value("${RAILWAY_PROJECT_ID:}")String project){this.jdbc=jdbc;this.residents=residents;this.moderation=moderation;this.limiter=limiter;this.key=key;proxy=!project.isBlank();}
 private void rate(HttpServletRequest request){String ip=request.getRemoteAddr();if(proxy&&request.getHeader("X-Forwarded-For")!=null){var hops=request.getHeader("X-Forwarded-For").split(",");var last=hops[hops.length-1].trim();if(last.matches("[0-9a-fA-F:.]+"))ip=last;}if(!limiter.acquire("reputation:"+ip).allowed())throw new ResponseStatusException(HttpStatus.TOO_MANY_REQUESTS,"Please try again in a minute");}
 private Map<String,Object> provider(String slug,UUID id,boolean lock){var rows=jdbc.queryForList("SELECT id,name,is_verified,verification_checked_at,rating,review_count FROM provider WHERE id=? AND community_id=? AND status='active'"+(lock?" FOR UPDATE":""),id,residents.community(slug));if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Provider not found in this community");return rows.getFirst();}
 private void operator(String auth){if(key.isBlank())throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Configure CAMPAIGN_ADMIN_TOKEN in Railway");String supplied=auth!=null&&auth.startsWith("Bearer ")?auth.substring(7):"";if(!MessageDigest.isEqual(key.getBytes(StandardCharsets.UTF_8),supplied.getBytes(StandardCharsets.UTF_8)))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Operator key required");}
 private void aggregate(UUID id){jdbc.update("UPDATE provider SET rating=COALESCE((SELECT ROUND(AVG(stars)::numeric,2) FROM provider_review WHERE provider_id=? AND NOT hidden),0),review_count=(SELECT COUNT(*) FROM provider_review WHERE provider_id=? AND NOT hidden) WHERE id=?",id,id,id);}
 @GetMapping("/providers/{id}/reputation") public Map<String,Object> publicReviews(@PathVariable String slug,@PathVariable UUID id,@RequestParam(defaultValue="0")int offset){if(offset<0||offset>10000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid page");var p=provider(slug,id,false);return Map.of("provider",p,"reviews",jdbc.queryForList("SELECT r.stars,r.body,r.updated_at,CASE WHEN p.share_name THEN p.name ELSE 'A neighbour' END AS name FROM provider_review r JOIN resident_profile p ON p.id=r.resident_id WHERE r.provider_id=? AND NOT r.hidden ORDER BY r.updated_at DESC,r.resident_id LIMIT 20 OFFSET ?",id,offset));}
 @GetMapping("/providers/{id}/reputation/mine") public Map<String,Object> mine(@PathVariable String slug,@PathVariable UUID id,@RequestHeader(value="Authorization",required=false)String auth){UUID resident=residents.authorize(slug,auth);provider(slug,id,false);return Map.of("feedback",jdbc.queryForList("SELECT CASE WHEN answered_at IS NULL THEN NULL ELSE outcome END AS outcome,contacted_at,answered_at FROM provider_contact_feedback WHERE resident_id=? AND provider_id=?",resident,id),"reviews",jdbc.queryForList("SELECT stars,body,hidden FROM provider_review WHERE resident_id=? AND provider_id=?",resident,id));}
 @PostMapping("/providers/{id}/contact") public void contact(@PathVariable String slug,@PathVariable UUID id,@RequestHeader(value="Authorization",required=false)String auth,HttpServletRequest request){rate(request);UUID resident=residents.authorize(slug,auth);provider(slug,id,false);jdbc.update("INSERT INTO provider_contact_feedback(resident_id,provider_id) VALUES(?,?) ON CONFLICT(resident_id,provider_id) DO UPDATE SET contacted_at=NOW()",resident,id);}
 public record Feedback(String outcome){}
 @PutMapping("/providers/{id}/feedback") public void feedback(@PathVariable String slug,@PathVariable UUID id,@RequestHeader(value="Authorization",required=false)String auth,@RequestBody Feedback feedback,HttpServletRequest request){rate(request);UUID resident=residents.authorize(slug,auth);provider(slug,id,false);if(!Set.of("waiting","connected","not_connected").contains(feedback.outcome()==null?"":feedback.outcome()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Choose a connection outcome");if(jdbc.update("UPDATE provider_contact_feedback SET outcome=?,answered_at=NOW() WHERE resident_id=? AND provider_id=?",feedback.outcome(),resident,id)==0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Record a contact attempt first");}
 public record Review(Integer stars,String body,boolean interacted){}
 @PutMapping("/providers/{id}/review") @Transactional public void review(@PathVariable String slug,@PathVariable UUID id,@RequestHeader(value="Authorization",required=false)String auth,@RequestBody Review review,HttpServletRequest request){rate(request);UUID resident=residents.authorize(slug,auth);if(!review.interacted()||review.stars()==null||review.stars()<1||review.stars()>5||review.body()!=null&&review.body().length()>1000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Confirm your interaction and choose 1–5 stars");String body=review.body()==null?"":review.body().trim();if(!body.isEmpty()){var decision=moderation.check(body);if(decision==MessageModerationService.Decision.BLOCK)throw new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,MessageModerationService.BLOCK_REPLY);if(decision!=MessageModerationService.Decision.ALLOW)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Could not check the review. Please retry");}provider(slug,id,true);
 if(!Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM provider_contact_feedback WHERE resident_id=? AND provider_id=? AND outcome='connected')",Boolean.class,resident,id)))throw new ResponseStatusException(HttpStatus.CONFLICT,"Confirm you connected before leaving a review");
 jdbc.update("INSERT INTO provider_review(resident_id,provider_id,stars,body) VALUES(?,?,?,?) ON CONFLICT(resident_id,provider_id) DO UPDATE SET stars=excluded.stars,body=excluded.body,updated_at=NOW()",resident,id,review.stars(),body);aggregate(id);}
 @DeleteMapping("/providers/{id}/review") @Transactional public void delete(@PathVariable String slug,@PathVariable UUID id,@RequestHeader(value="Authorization",required=false)String auth,HttpServletRequest request){rate(request);UUID resident=residents.authorize(slug,auth);provider(slug,id,true);jdbc.update("DELETE FROM provider_review WHERE resident_id=? AND provider_id=?",resident,id);aggregate(id);}
 @GetMapping("/admin/reputation") public Map<String,Object> workspace(@PathVariable String slug,@RequestHeader(value="Authorization",required=false)String auth){operator(auth);UUID c=residents.community(slug);return Map.of("providers",jdbc.queryForList("SELECT id,name,shop_name,flat_number,whatsapp_number,is_verified,verification_checked_at,rating,review_count FROM provider WHERE community_id=? AND status='active' ORDER BY shop_name",c),"reviews",jdbc.queryForList("SELECT r.resident_id,r.provider_id,r.stars,r.body,r.hidden,p.shop_name FROM provider_review r JOIN provider p ON p.id=r.provider_id WHERE p.community_id=? ORDER BY r.updated_at DESC LIMIT 200",c),"feedback",jdbc.queryForList("SELECT p.id,p.shop_name,CASE WHEN f.answered_at IS NULL THEN 'not_answered' ELSE f.outcome END AS outcome,COUNT(*) AS count FROM provider_contact_feedback f JOIN provider p ON p.id=f.provider_id WHERE p.community_id=? GROUP BY p.id,p.shop_name,CASE WHEN f.answered_at IS NULL THEN 'not_answered' ELSE f.outcome END ORDER BY p.shop_name",c));}
 public record Verification(boolean verified,boolean identityChecked,boolean flatChecked,boolean contactChecked,String evidence){}
 @PostMapping("/admin/reputation/{id}/verify") @Transactional public void verify(@PathVariable String slug,@PathVariable UUID id,@RequestHeader(value="Authorization",required=false)String auth,@RequestBody Verification v){operator(auth);if(v.evidence()==null||v.evidence().isBlank()||v.evidence().length()>1000||v.verified()&&!(v.identityChecked()&&v.flatChecked()&&v.contactChecked()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Record all three checks and private evidence before verification");var p=provider(slug,id,true);if(v.verified()&&p.get("name").toString().toLowerCase(Locale.ROOT).contains("demo"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Fictional providers cannot be verified");jdbc.update("UPDATE provider SET is_verified=?,verification_checked_at=NOW() WHERE id=?",v.verified(),id);jdbc.update("INSERT INTO provider_verification_audit(id,provider_id,verified,identity_checked,flat_checked,contact_checked,evidence) VALUES(?,?,?,?,?,?,?)",UUID.randomUUID(),id,v.verified(),v.identityChecked(),v.flatChecked(),v.contactChecked(),v.evidence().trim());}
 public record Visibility(UUID residentId,boolean hidden,String reason){}
 @PostMapping("/admin/reputation/{id}/moderate") @Transactional public void moderate(@PathVariable String slug,@PathVariable UUID id,@RequestHeader(value="Authorization",required=false)String auth,@RequestBody Visibility v){operator(auth);if(v.residentId()==null||v.reason()==null||v.reason().isBlank()||v.reason().length()>1000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Give a moderation reason");provider(slug,id,true);if(jdbc.update("UPDATE provider_review SET hidden=? WHERE provider_id=? AND resident_id=?",v.hidden(),id,v.residentId())==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Review not found");jdbc.update("INSERT INTO provider_review_moderation_audit(id,provider_id,resident_id,hidden,reason) VALUES(?,?,?,?,?)",UUID.randomUUID(),id,v.residentId(),v.hidden(),v.reason().trim());aggregate(id);}
}
